# Generated by Django 4.1.1 on 2022-09-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recomendations',
            new_name='Recomendation',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField(default=0, verbose_name='Порядковый номер (UNIQUE ONLY)')),
                ('image', models.ImageField(upload_to='images', verbose_name='Фотография')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.person', verbose_name='Соискатель')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
