# Generated by Django 4.1.1 on 2022-09-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_recomendations_recomendation_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendation',
            name='resume',
            field=models.ManyToManyField(blank=True, related_name='recomendations', to='main.resume', verbose_name='Резюме'),
        ),
    ]
