# Generated by Django 4.1.1 on 2022-09-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_recomendation_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.SmallIntegerField(verbose_name='TG_id')),
                ('first_visit', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
            ],
        ),
    ]
