# Generated by Django 4.1.1 on 2022-09-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiographyChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField(default=0, verbose_name='Порядковый номер (UNIQUE ONLY)')),
                ('title', models.CharField(max_length=25, verbose_name='Название раздела')),
                ('text', models.TextField(verbose_name='Текст')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biography_chapters', to='main.person', verbose_name='Соискатель')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biography_chapter', to='main.photo', verbose_name='Фотография')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
