# Generated by Django 4.1.1 on 2022-09-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_biographychapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='yCGpkvMm', max_length=50, unique=True, verbose_name='Никнейм'),
        ),
    ]
