# Generated by Django 4.1.1 on 2022-09-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_person_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='telegram_id',
            field=models.SmallIntegerField(default=0, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='QZoIVSqC', max_length=50, unique=True, verbose_name='Никнейм'),
        ),
    ]
