# Generated by Django 4.1.1 on 2022-09-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_person_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='ZjHZoGQC', max_length=50, unique=True, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='project',
            name='develop_stack',
            field=models.ManyToManyField(related_name='projects', to='main.hardskill', verbose_name='Стек'),
        ),
    ]
