# Generated by Django 4.1.1 on 2022-10-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_person_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='softskill',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='softskill',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='softskills', to='main.person', verbose_name='Соискатель'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='lDVLYink', max_length=50, unique=True, verbose_name='Никнейм'),
        ),
    ]
