# Generated by Django 4.1.1 on 2022-10-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_softskill_description_softskill_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highereducation',
            name='department',
            field=models.CharField(default='Дневное', max_length=100, verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='WNWbXQNg', max_length=50, unique=True, verbose_name='Никнейм'),
        ),
    ]
