# Generated by Django 4.1.1 on 2022-10-19 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_highereducation_department_alter_person_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highereducation',
            name='finished_at',
            field=models.SmallIntegerField(blank=True, help_text='Введите год в формате YYYY (напр. 2012)', null=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}$')], verbose_name='Год окончания обучения (напр. 2012)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='sSNmbGUZ', max_length=50, unique=True, verbose_name='Никнейм'),
        ),
    ]
