# Generated by Django 4.1.1 on 2022-10-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_resume_places_of_work_alter_person_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeofwork',
            name='summary',
            field=models.CharField(blank=True, help_text='заполнять если не заполнено начало и окончание', max_length=100, null=True, verbose_name='Суммарно проработал'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='xIwobUaq', max_length=50, unique=True, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='placeofwork',
            name='started_at',
            field=models.DateField(blank=True, null=True, verbose_name='Начало работы'),
        ),
    ]
