# Generated by Django 4.1.1 on 2022-10-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_placeofwork_summary_alter_person_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='about_candidate',
            field=models.TextField(blank=True, verbose_name='Коротко о себе'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='BQYTOljX', max_length=50, unique=True, verbose_name='Никнейм'),
        ),
    ]
