# Generated by Django 4.1.1 on 2022-10-19 18:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_resume_about_candidate_alter_person_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='IkgHWrkX', max_length=50, unique=True, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='about_candidate',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Коротко о себе'),
        ),
    ]
