# Generated by Django 4.1.1 on 2022-10-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_person_nickname_alter_resume_about_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='wmzHnyXu', max_length=50, unique=True, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='placeofwork',
            name='company',
            field=models.CharField(max_length=200, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='placeofwork',
            name='post',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
    ]
