# Generated by Django 4.1.1 on 2022-10-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_person_nickname_alter_placeofwork_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommender', models.CharField(max_length=100, verbose_name='Рекомендатель')),
                ('company', models.CharField(max_length=50, verbose_name='Компания')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='DVnJrQPF', max_length=50, unique=True, verbose_name='Никнейм'),
        ),
        migrations.DeleteModel(
            name='Recomendation',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='main.person', verbose_name='Соискатель'),
        ),
        migrations.AddField(
            model_name='resume',
            name='recommendations',
            field=models.ManyToManyField(blank=True, to='main.recommendation', verbose_name='Рекоммендации'),
        ),
    ]
