# Generated by Django 4.1.1 on 2022-10-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_recommendation_alter_person_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='advantages',
            field=models.TextField(blank=True, help_text='заполнять по одному через Enter', verbose_name='Ожидания'),
        ),
        migrations.AddField(
            model_name='resume',
            name='expectations',
            field=models.TextField(blank=True, help_text='заполнять по одному через Enter', verbose_name='Ожидания'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='RfHFDgBb', max_length=50, unique=True, verbose_name='Никнейм'),
        ),
    ]
