# Generated by Django 4.1.1 on 2022-10-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_person_nickname_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biographychapter',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название раздела'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='WqwGvkoQ', max_length=50, unique=True, verbose_name='Никнейм'),
        ),
    ]
