# Generated by Django 4.1.1 on 2022-10-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_biographychapter_title_alter_person_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biographychapter',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='biography_chapter', to='main.photo', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='aixqYicP', max_length=50, unique=True, verbose_name='Никнейм'),
        ),
    ]
