# Generated by Django 4.1.1 on 2022-10-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_biographychapter_photo_alter_person_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Использовать как основную'),
        ),
        migrations.AddField(
            model_name='photo',
            name='show_in_main',
            field=models.BooleanField(default=False, verbose_name='Использовать на главной'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='UqQTruxY', max_length=50, unique=True, verbose_name='Никнейм'),
        ),
    ]
